/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-22 at 22:22:19 UTC 
 * Modify at your own risk.
 */

package com.mycompany.services.questionentityendpoint.model;

/**
 * Model definition for QuestionEntity.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the questionentityendpoint. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class QuestionEntity extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer answer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> choices;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String question;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAnswer() {
    return answer;
  }

  /**
   * @param answer answer or {@code null} for none
   */
  public QuestionEntity setAnswer(java.lang.Integer answer) {
    this.answer = answer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getChoices() {
    return choices;
  }

  /**
   * @param choices choices or {@code null} for none
   */
  public QuestionEntity setChoices(java.util.List<java.lang.String> choices) {
    this.choices = choices;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public QuestionEntity setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuestion() {
    return question;
  }

  /**
   * @param question question or {@code null} for none
   */
  public QuestionEntity setQuestion(java.lang.String question) {
    this.question = question;
    return this;
  }

  @Override
  public QuestionEntity set(String fieldName, Object value) {
    return (QuestionEntity) super.set(fieldName, value);
  }

  @Override
  public QuestionEntity clone() {
    return (QuestionEntity) super.clone();
  }

}
