/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-22 at 22:22:19 UTC 
 * Modify at your own risk.
 */

package com.mycompany.services.questionentityendpoint;

/**
 * Service definition for Questionentityendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link QuestionentityendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Questionentityendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the questionentityendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://movizquiz.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "questionentityendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Questionentityendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Questionentityendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getQuestionEntity".
   *
   * This request holds the parameters needed by the questionentityendpoint server.  After setting any
   * optional parameters, call the {@link GetQuestionEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetQuestionEntity getQuestionEntity(java.lang.String id) throws java.io.IOException {
    GetQuestionEntity result = new GetQuestionEntity(id);
    initialize(result);
    return result;
  }

  public class GetQuestionEntity extends QuestionentityendpointRequest<com.mycompany.services.questionentityendpoint.model.QuestionEntity> {

    private static final String REST_PATH = "questionentity/{id}";

    /**
     * Create a request for the method "getQuestionEntity".
     *
     * This request holds the parameters needed by the the questionentityendpoint server.  After
     * setting any optional parameters, call the {@link GetQuestionEntity#execute()} method to invoke
     * the remote operation. <p> {@link GetQuestionEntity#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetQuestionEntity(java.lang.String id) {
      super(Questionentityendpoint.this, "GET", REST_PATH, null, com.mycompany.services.questionentityendpoint.model.QuestionEntity.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetQuestionEntity setAlt(java.lang.String alt) {
      return (GetQuestionEntity) super.setAlt(alt);
    }

    @Override
    public GetQuestionEntity setFields(java.lang.String fields) {
      return (GetQuestionEntity) super.setFields(fields);
    }

    @Override
    public GetQuestionEntity setKey(java.lang.String key) {
      return (GetQuestionEntity) super.setKey(key);
    }

    @Override
    public GetQuestionEntity setOauthToken(java.lang.String oauthToken) {
      return (GetQuestionEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public GetQuestionEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetQuestionEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetQuestionEntity setQuotaUser(java.lang.String quotaUser) {
      return (GetQuestionEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetQuestionEntity setUserIp(java.lang.String userIp) {
      return (GetQuestionEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetQuestionEntity setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetQuestionEntity set(String parameterName, Object value) {
      return (GetQuestionEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertQuestionEntity".
   *
   * This request holds the parameters needed by the questionentityendpoint server.  After setting any
   * optional parameters, call the {@link InsertQuestionEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mycompany.services.questionentityendpoint.model.QuestionEntity}
   * @return the request
   */
  public InsertQuestionEntity insertQuestionEntity(com.mycompany.services.questionentityendpoint.model.QuestionEntity content) throws java.io.IOException {
    InsertQuestionEntity result = new InsertQuestionEntity(content);
    initialize(result);
    return result;
  }

  public class InsertQuestionEntity extends QuestionentityendpointRequest<com.mycompany.services.questionentityendpoint.model.QuestionEntity> {

    private static final String REST_PATH = "questionentity";

    /**
     * Create a request for the method "insertQuestionEntity".
     *
     * This request holds the parameters needed by the the questionentityendpoint server.  After
     * setting any optional parameters, call the {@link InsertQuestionEntity#execute()} method to
     * invoke the remote operation. <p> {@link InsertQuestionEntity#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.questionentityendpoint.model.QuestionEntity}
     * @since 1.13
     */
    protected InsertQuestionEntity(com.mycompany.services.questionentityendpoint.model.QuestionEntity content) {
      super(Questionentityendpoint.this, "POST", REST_PATH, content, com.mycompany.services.questionentityendpoint.model.QuestionEntity.class);
    }

    @Override
    public InsertQuestionEntity setAlt(java.lang.String alt) {
      return (InsertQuestionEntity) super.setAlt(alt);
    }

    @Override
    public InsertQuestionEntity setFields(java.lang.String fields) {
      return (InsertQuestionEntity) super.setFields(fields);
    }

    @Override
    public InsertQuestionEntity setKey(java.lang.String key) {
      return (InsertQuestionEntity) super.setKey(key);
    }

    @Override
    public InsertQuestionEntity setOauthToken(java.lang.String oauthToken) {
      return (InsertQuestionEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertQuestionEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertQuestionEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertQuestionEntity setQuotaUser(java.lang.String quotaUser) {
      return (InsertQuestionEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertQuestionEntity setUserIp(java.lang.String userIp) {
      return (InsertQuestionEntity) super.setUserIp(userIp);
    }

    @Override
    public InsertQuestionEntity set(String parameterName, Object value) {
      return (InsertQuestionEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listQuestionEntity".
   *
   * This request holds the parameters needed by the questionentityendpoint server.  After setting any
   * optional parameters, call the {@link ListQuestionEntity#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListQuestionEntity listQuestionEntity() throws java.io.IOException {
    ListQuestionEntity result = new ListQuestionEntity();
    initialize(result);
    return result;
  }

  public class ListQuestionEntity extends QuestionentityendpointRequest<com.mycompany.services.questionentityendpoint.model.CollectionResponseQuestionEntity> {

    private static final String REST_PATH = "questionentity";

    /**
     * Create a request for the method "listQuestionEntity".
     *
     * This request holds the parameters needed by the the questionentityendpoint server.  After
     * setting any optional parameters, call the {@link ListQuestionEntity#execute()} method to invoke
     * the remote operation. <p> {@link ListQuestionEntity#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListQuestionEntity() {
      super(Questionentityendpoint.this, "GET", REST_PATH, null, com.mycompany.services.questionentityendpoint.model.CollectionResponseQuestionEntity.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListQuestionEntity setAlt(java.lang.String alt) {
      return (ListQuestionEntity) super.setAlt(alt);
    }

    @Override
    public ListQuestionEntity setFields(java.lang.String fields) {
      return (ListQuestionEntity) super.setFields(fields);
    }

    @Override
    public ListQuestionEntity setKey(java.lang.String key) {
      return (ListQuestionEntity) super.setKey(key);
    }

    @Override
    public ListQuestionEntity setOauthToken(java.lang.String oauthToken) {
      return (ListQuestionEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public ListQuestionEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListQuestionEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListQuestionEntity setQuotaUser(java.lang.String quotaUser) {
      return (ListQuestionEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListQuestionEntity setUserIp(java.lang.String userIp) {
      return (ListQuestionEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListQuestionEntity setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListQuestionEntity setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListQuestionEntity set(String parameterName, Object value) {
      return (ListQuestionEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeQuestionEntity".
   *
   * This request holds the parameters needed by the questionentityendpoint server.  After setting any
   * optional parameters, call the {@link RemoveQuestionEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveQuestionEntity removeQuestionEntity(java.lang.String id) throws java.io.IOException {
    RemoveQuestionEntity result = new RemoveQuestionEntity(id);
    initialize(result);
    return result;
  }

  public class RemoveQuestionEntity extends QuestionentityendpointRequest<Void> {

    private static final String REST_PATH = "questionentity/{id}";

    /**
     * Create a request for the method "removeQuestionEntity".
     *
     * This request holds the parameters needed by the the questionentityendpoint server.  After
     * setting any optional parameters, call the {@link RemoveQuestionEntity#execute()} method to
     * invoke the remote operation. <p> {@link RemoveQuestionEntity#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveQuestionEntity(java.lang.String id) {
      super(Questionentityendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveQuestionEntity setAlt(java.lang.String alt) {
      return (RemoveQuestionEntity) super.setAlt(alt);
    }

    @Override
    public RemoveQuestionEntity setFields(java.lang.String fields) {
      return (RemoveQuestionEntity) super.setFields(fields);
    }

    @Override
    public RemoveQuestionEntity setKey(java.lang.String key) {
      return (RemoveQuestionEntity) super.setKey(key);
    }

    @Override
    public RemoveQuestionEntity setOauthToken(java.lang.String oauthToken) {
      return (RemoveQuestionEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveQuestionEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveQuestionEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveQuestionEntity setQuotaUser(java.lang.String quotaUser) {
      return (RemoveQuestionEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveQuestionEntity setUserIp(java.lang.String userIp) {
      return (RemoveQuestionEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveQuestionEntity setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveQuestionEntity set(String parameterName, Object value) {
      return (RemoveQuestionEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateQuestionEntity".
   *
   * This request holds the parameters needed by the questionentityendpoint server.  After setting any
   * optional parameters, call the {@link UpdateQuestionEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mycompany.services.questionentityendpoint.model.QuestionEntity}
   * @return the request
   */
  public UpdateQuestionEntity updateQuestionEntity(com.mycompany.services.questionentityendpoint.model.QuestionEntity content) throws java.io.IOException {
    UpdateQuestionEntity result = new UpdateQuestionEntity(content);
    initialize(result);
    return result;
  }

  public class UpdateQuestionEntity extends QuestionentityendpointRequest<com.mycompany.services.questionentityendpoint.model.QuestionEntity> {

    private static final String REST_PATH = "questionentity";

    /**
     * Create a request for the method "updateQuestionEntity".
     *
     * This request holds the parameters needed by the the questionentityendpoint server.  After
     * setting any optional parameters, call the {@link UpdateQuestionEntity#execute()} method to
     * invoke the remote operation. <p> {@link UpdateQuestionEntity#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.questionentityendpoint.model.QuestionEntity}
     * @since 1.13
     */
    protected UpdateQuestionEntity(com.mycompany.services.questionentityendpoint.model.QuestionEntity content) {
      super(Questionentityendpoint.this, "PUT", REST_PATH, content, com.mycompany.services.questionentityendpoint.model.QuestionEntity.class);
    }

    @Override
    public UpdateQuestionEntity setAlt(java.lang.String alt) {
      return (UpdateQuestionEntity) super.setAlt(alt);
    }

    @Override
    public UpdateQuestionEntity setFields(java.lang.String fields) {
      return (UpdateQuestionEntity) super.setFields(fields);
    }

    @Override
    public UpdateQuestionEntity setKey(java.lang.String key) {
      return (UpdateQuestionEntity) super.setKey(key);
    }

    @Override
    public UpdateQuestionEntity setOauthToken(java.lang.String oauthToken) {
      return (UpdateQuestionEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateQuestionEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateQuestionEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateQuestionEntity setQuotaUser(java.lang.String quotaUser) {
      return (UpdateQuestionEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateQuestionEntity setUserIp(java.lang.String userIp) {
      return (UpdateQuestionEntity) super.setUserIp(userIp);
    }

    @Override
    public UpdateQuestionEntity set(String parameterName, Object value) {
      return (UpdateQuestionEntity) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Questionentityendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Questionentityendpoint}. */
    @Override
    public Questionentityendpoint build() {
      return new Questionentityendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link QuestionentityendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setQuestionentityendpointRequestInitializer(
        QuestionentityendpointRequestInitializer questionentityendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(questionentityendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
